In [1]:
%env CUDA_LAUNCH_BLOCKING=1
%load_ext autoreload
%autoreload complete
# %aimport ...

import sys
import importlib
import warnings

importlib.invalidate_caches()

for mod_name in list(sys.modules):
    if not (str.startswith(mod_name, "robotodo") or str.startswith(mod_name, "tensorspecs")):
        continue
    try:
        importlib.reload(sys.modules[mod_name])
    except Exception as error:
        warnings.warn(f"{error}")


env: CUDA_LAUNCH_BLOCKING=1


In [2]:
from robotodo.engines.isaac._kernel import configure_default_kernel
configure_default_kernel(
    extra_argv=[
        "--/log/file=/tmp/todo-isaacsim.log",
        "--/app/settings/loadUserConfig=false",
        # "--/log/enableStandardStreamOutput=true",
        "--/app/enableStdoutOutput=true",
        # "--no-window",
        # TODO
        # "--/app/content/emptyStageOnStart=false",
        # "--/app/asyncRendering=true",
        # "--enable", "isaacsim.exp.full",
        # "--/app/vulkan=",
    ], 
    kit_path="isaacsim.exp.full.kit",
)

In [3]:
# TODO 
from robotodo.engines.isaac.builders import load_usd_scene

# TODO set up axis
scene = await load_usd_scene(
    "https://omniverse-content-production.s3-us-west-2.amazonaws.com/Assets/Isaac/5.0/Isaac/Environments/Simple_Room/simple_room.usd",
    # "https://omniverse-content-production.s3-us-west-2.amazonaws.com/Assets/Isaac/5.0/Isaac/Environments/Grid/default_environment.usd",
    # "https://omniverse-content-production.s3-us-west-2.amazonaws.com/Assets/Isaac/5.0/Isaac/Environments/Grid/gridroom_black.usd",
)

[Warning] [simulation_app] Interactive python shell detected but ISAAC_JUPYTER_KERNEL was not set. Problems with asyncio may occur
[Warning] [simulation_app] Please use Isaac Sim Python 3 kernel instead of the default Python 3 Kernel
[0.063s] [ext: omni.kit.async_engine-0.0.3] startup
[0.321s] [ext: omni.metrics.core-0.0.3] startup
[0.321s] [ext: omni.client.lib-1.1.0] startup
[0.335s] [ext: omni.blobkey-1.1.2] startup
[0.335s] [ext: omni.stats-1.0.1] startup
[0.336s] [ext: omni.datastore-0.0.0] startup
[0.342s] [ext: omni.client-1.3.0] startup
[0.397s] [ext: omni.ujitso.default-1.0.0] startup
[0.399s] [ext: omni.hsscclient-1.1.2] startup
[0.404s] [ext: omni.gpu_foundation.shadercache.vulkan-1.0.0] startup
[0.407s] [ext: omni.assets.plugins-0.0.0] startup
[0.408s] [ext: omni.gpu_foundation-0.0.0] startup
[0.416s] [ext: carb.windowing.plugins-1.0.0] startup
[0.423s] [ext: omni.kit.renderer.init-0.0.0] startup

|----------------------------------------------------------------------------

2025-11-05T11:51:33Z [12,989ms] [Error] [isaacsim.ros2.bridge.impl.extension] ROS2 Bridge startup failed


[13.875s] [ext: omni.kit.registry.nucleus-0.0.0] startup


2025-11-05T11:51:34Z [14,193ms] [Error] [carb.graphics-vulkan.plugin] Could not get NGX parameters block because NGX isn't enabled.
2025-11-05T11:51:34Z [14,193ms] [Error] [carb.graphics-vulkan.plugin] Failed to create NGX context.
2025-11-05T11:51:34Z [14,303ms] [Error] [rtx.optixdenoising73.plugin] Failed to create an Optix adaptor for device 0


[14.392s] app ready


In [4]:
from robotodo.engines.isaac.scene import Scene
from robotodo.engines.isaac.builders import load_urdf, load_usd, build_camera, builder, EntityBodyKind
from robotodo.utils.pose import Pose


# scene = Scene(_kernel=kernel)


panda = await load_urdf(
    "./todo-curobo-sample-configs/franka/franka_description/franka_panda.urdf", 
    scene=scene, 
    path="/Panda",
    fix_root_link=True,
)


mug = await load_usd(
    "https://omniverse-content-production.s3-us-west-2.amazonaws.com/Assets/Isaac/5.0/Isaac/Props/Mugs/SM_Mug_A2.usd",
    scene=scene,
    path="/Mug",
)
builder.reset(mug, body_kind=EntityBodyKind.RIGID)

mug.collision.enabled = True
mug.pose = Pose(p=[.5, .5, .5])



In [5]:
mug.pose

Pose(p=array([[0.5, 0.5, 0.5]]), q=array([[0., 0., 0., 1.]]))

[22.513s] Isaac Sim Full App is loaded.


In [12]:
mug.pose_in_parent

Pose(p=array([[1., 1., 1.]]), q=array([[0., 0., 0., 1.]]))

In [13]:
mug.pose_in_parent = Pose([1, 1, 1], [.5, 0, 0, 1])

In [36]:

x, _ = mug._usd_prim_helper._usd_xform_cache.GetLocalTransformation(mug._usd_prims[0])


import numpy

Pose.from_matrix(
x.RemoveScaleShear().GetTranspose()

)


# x


Pose(p=array([1., 1., 1.]), q=array([0., 0., 0., 1.]))

In [41]:
x

Gf.Matrix4d(0.009999999776482582, 0.0, 0.0, 0.0,
            0.0, 0.009999999776482582, 0.0, 0.0,
            0.0, 0.0, 0.009999999776482582, 0.0,
            1.0, 1.0, 1.0, 1.0)

In [40]:
import pxr

pxr.UsdGeom.Camera

pxr.UsdGeom.Camera

In [43]:
import numpy
numpy.eye(4).T

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [51]:
import pxr
pxr.Gf.Transform(x)

Gf.Transform(translation = Gf.Vec3d(1.0, 1.0, 1.0), 
             scale = Gf.Vec3d(0.009999999776482582, 0.009999999776482582, 0.009999999776482582))

In [52]:
pxr.Gf.Transform?

Docstring:      <no docstring>
Init docstring:
Initializer used by 3x code.

Initializer used by old 2x code. (Deprecated)

Initializer used by old 2x code. (Deprecated)
File:           ~/lab/robotodo/.conda/lib/python3.11/site-packages/omni/data/Kit/Isaac-Sim Full/5.0/exts/3/omni.usd.libs-1.0.1+8131b85d.lx64.r.cp311/pxr/Gf/__init__.py
Type:           class
Subclasses:     

In [38]:
numpy.matmul(
    x.RemoveScaleShear().GetTranspose(),
    numpy.asarray([
            [0, 0, -1, 0], 
            [-1, 0, 0, 0], 
            [0, 1, 0, 0], 
            [0, 0, 0, 1],
        ])
)

array([[ 0.,  0., -1.,  1.],
       [-1.,  0.,  0.,  1.],
       [ 0.,  1.,  0.,  1.],
       [ 0.,  0.,  0.,  1.]])

In [ ]:
x.RemoveScaleShear().GetTranspose() * numpy.asarray([
            [0, 0, -1, 0], 
            [-1, 0, 0, 0], 
            [0, 1, 0, 0], 
            [0, 0, 0, 1],
        ])

array([[ 0.,  0., -0.,  0.],
       [-0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [28]:
Pose.from_matrix(numpy.asarray([
            [0, 0, -1, 0], 
            [-1, 0, 0, 0], 
            [0, 1, 0, 0], 
            [0, 0, 0, 1],
        ])).to_matrix()

array([[ 0.,  0., -1.,  0.],
       [-1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [16]:
scene.autostepping = True

In [14]:
camera = await build_camera(
    scene=scene,
    path="/Panda/panda_hand/Camera",
)

In [15]:
await camera.read_rgba()

Module robotodo.engines.isaac.sensors f0dd58f load on device 'cuda:0' took 0.32 ms  (cached)


tensor([[[[  3,   3,   3, 255],
          [ 31,  28,  24, 255],
          [ 31,  28,  24, 255],
          ...,
          [ 20,  18,  14, 255],
          [ 20,  18,  14, 255],
          [ 18,  16,  13, 255]],

         [[ 11,   9,   8, 255],
          [ 31,  28,  24, 255],
          [ 31,  28,  24, 255],
          ...,
          [ 21,  19,  16, 255],
          [ 21,  19,  16, 255],
          [ 20,  18,  15, 255]],

         [[ 11,   9,   8, 255],
          [ 31,  28,  24, 255],
          [ 31,  28,  24, 255],
          ...,
          [ 21,  19,  16, 255],
          [ 21,  19,  16, 255],
          [ 20,  18,  15, 255]],

         ...,

         [[  6,   6,   4, 255],
          [ 21,  19,  15, 255],
          [ 21,  19,  15, 255],
          ...,
          [ 22,  19,  16, 255],
          [ 22,  19,  16, 255],
          [ 21,  18,  15, 255]],

         [[  6,   6,   4, 255],
          [ 21,  19,  15, 255],
          [ 21,  19,  15, 255],
          ...,
          [ 22,  19,  16, 255],
      

In [25]:
import matplotlib.pyplot as plt


plt.imshow((await camera.read_rgba()).cpu()[0])

Warp CUDA error 700: an illegal memory access was encountered (in function cuda_launch_kernel, /builds/omniverse/warp/warp/native/warp.cu:4057)
Warp CUDA error 700: an illegal memory access was encountered (in function free_device_async, /builds/omniverse/warp/warp/native/warp.cu:659)


RuntimeError: CUDA error: an illegal memory access was encountered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


2025-11-06T05:02:53Z [61,892,504ms] [Error] [carb.cudainterop.plugin] CUDA error 700: cudaErrorIllegalAddress - an illegal memory access was encountered)
2025-11-06T05:02:53Z [61,892,504ms] [Error] [carb.cudainterop.plugin] Failed to wait on external semaphore in CUDA.
2025-11-06T05:02:53Z [61,892,504ms] [Error] [gpu.foundation.plugin] Wait for external semaphore failed in CUDA submission in command list "Render graph command list (Render queue 0, device 0, frame submission index 1)"
2025-11-06T05:02:53Z [61,892,511ms] [Error] [carb.cudainterop.plugin] CUDA error 700: cudaErrorIllegalAddress - an illegal memory access was encountered)
2025-11-06T05:02:53Z [61,892,511ms] [Error] [carb.cudainterop.plugin] Failed to wait on external semaphore in CUDA.
2025-11-06T05:02:53Z [61,892,511ms] [Error] [gpu.foundation.plugin] Wait for external semaphore failed in CUDA submission in command list "Render graph command list (Render queue 0, device 0, frame submission index 2)"
2025-11-06T05:02:53Z [

In [20]:
camera.pose_in_parent = Pose()

In [24]:
camera

In [23]:
scene.viewer.draw_pose(camera.pose)

In [ ]:
import numpy

from tensorspecs import TensorLike


# TODO rm?/?
class _TODOPose:
    @classmethod
    def from_matrix(cls, matrix: TensorLike["* 4 4"]):
        r"""
        TODO doc
        """

        self = cls.__new__(cls)
        self._matrix = matrix
        return self

    def __init__(self, p: TensorLike["* p:3"], q: TensorLike["* q:4"]):
        r"""
        TODO doc
        """

        self._matrix = ...

    @property
    def matrix(self):
        return self._matrix
    
    def inv(self):
        return _TODOPose.from_matrix(
            numpy.linalg.inv(self._matrix)
        )

    def __mul__(self, other: "_TODOPose"):
        return _TODOPose.from_matrix(
            numpy.matmul(
                self._matrix,
                other._matrix,
            )
        )

In [ ]:
from tensorspecs import TensorLike


class PositionF:
    @staticmethod
    def inv(pos: TensorLike["* xyz:3"]):
        return numpy.negative(pos)

    @staticmethod
    def compose(pos: TensorLike["* xyz:3"], pos_other: TensorLike["* xyz:3"]):
        return numpy.add(pos, pos_other)


class QuaternionF:
    @staticmethod
    def inv(quat: TensorLike["* xyzw:4"]):
        return numpy.multiply(
            quat,
            [-1, -1, -1, 1],
        )

    # TODO test against scipy
    @staticmethod
    def compose(quat: TensorLike["* xyzw:4"], quat_other: TensorLike["* xyzw:4"]):
        """
        TODO
        """

        q0 = numpy.asarray(quat)
        q1 = numpy.asarray(quat_other)

        v0, v1 = q0[..., :3], q1[..., :3]
        w0, w1 = q0[..., 3], q1[..., 3]

        cross = numpy.cross(q0[..., :3], q1[..., :3], axis=-1)

        vec = w0[..., None] * v1 + w1[..., None] * v0 + cross
        scal = w0 * w1 - numpy.sum(v0 * v1, axis=-1)

        return numpy.concatenate([vec, scal[..., None]], axis=-1)


from typing import Any

class _TODONextPose(Pose):
    def __repr__(self):
        return f"{Pose.__qualname__}(p={self.p!r}, q={self.q!r})"

    def __getitem__(self, index: tuple | Any):
        if not isinstance(index, tuple):
            index = tuple((index, ))
        return Pose(
            p=self.p[*index, :],
            q=self.q[*index, :],
        )

    # TODO wrong
    # def inv(self):
    #     return Pose(
    #         p=PositionF.inv(self.p),
    #         q=QuaternionF.inv(self.q),
    #     )

    # TODO wrong
    # def __mul__(self, other: "Pose"):
    #     return Pose(
    #         p=PositionF.compose(self.p, other.p),
    #         q=QuaternionF.compose(self.q, other.q),
    #     )
        


In [ ]:
def test_quat_compose():
    # TODO
    
    def _compose_quat(quat0, quat1):
        cross = numpy.cross(quat0[:3], quat1[:3])
        return numpy.asarray([
            quat0[3] * quat1[0] + quat1[3] * quat0[0] + cross[0],
            quat0[3] * quat1[1] + quat1[3] * quat0[1] + cross[1],
            quat0[3] * quat1[2] + quat1[3] * quat0[2] + cross[2],
            quat0[3] * quat1[3] - quat0[0] * quat1[0] - quat0[1] * quat1[1] - quat0[2] * quat1[2]
        ])

    a = numpy.asarray([0, 1, 0, 1])
    b = numpy.asarray([0, 4, 3, 1])

    _compose_quat(a, b), QuaternionF.compose([a, a], [b, b])

(array([ 3,  5,  3, -3]),
 array([[ 3,  5,  3, -3],
        [ 3,  5,  3, -3]]))

In [ ]:
import scipy
scipy.spatial.transform.Rotation.from_quat([ 0.5, -0.5, -0.5, -0.5]).approx_equal(
    scipy.spatial.transform.Rotation.from_quat([-1., 1., 1., 1.])
)
from robotodo.utils.pose import Pose

Pose.from_matrix(
    numpy.asarray([
            [0, -1, 0, 0], 
            [0, 0, 1, 0], 
            [-1, 0, 0, 0], 
            [0, 0, 0, 1],
        ])
)