# Articulations (Robots)

TODO WIP
TODO explain what articulations are

In [1]:
from robotodo.engines.isaac.scene import Scene

scene = Scene.load(
    "https://omniverse-content-production.s3-us-west-2.amazonaws.com/Assets/Isaac/5.0/Isaac/Environments/Grid/default_environment.usd",
)

In [2]:
# TODO remind users to use viewer if need be
# await scene.viewer.show()

In [3]:
from robotodo.engines.isaac.articulation import Articulation

panda = Articulation.load(
    "/World/Panda",
    "https://omniverse-content-production.s3-us-west-2.amazonaws.com/Assets/Isaac/5.0/Isaac/Robots/FrankaRobotics/FrankaPanda/franka.usd",
    scene=scene,
)
panda

Articulation(['/World/Panda'], scene=Scene())

In [4]:
# TODO
# panda.viewer.show()

TODO inform users abt urdf support

In [5]:
panda.links

{'panda_link0': Body(['/World/Panda/panda_link0'], scene=Scene()),
 'panda_link1': Body(['/World/Panda/panda_link1'], scene=Scene()),
 'panda_link2': Body(['/World/Panda/panda_link2'], scene=Scene()),
 'panda_link3': Body(['/World/Panda/panda_link3'], scene=Scene()),
 'panda_link4': Body(['/World/Panda/panda_link4'], scene=Scene()),
 'panda_link5': Body(['/World/Panda/panda_link5'], scene=Scene()),
 'panda_link6': Body(['/World/Panda/panda_link6'], scene=Scene()),
 'panda_link7': Body(['/World/Panda/panda_link7'], scene=Scene()),
 'panda_hand': Body(['/World/Panda/panda_hand'], scene=Scene()),
 'panda_leftfinger': Body(['/World/Panda/panda_leftfinger'], scene=Scene()),
 'panda_rightfinger': Body(['/World/Panda/panda_rightfinger'], scene=Scene())}

In [6]:
panda.joints

{'panda_joint1': Joint['panda_joint1'](['/World/Panda/panda_link0/panda_joint1'], scene=Scene()),
 'panda_joint2': Joint['panda_joint2'](['/World/Panda/panda_link1/panda_joint2'], scene=Scene()),
 'panda_joint3': Joint['panda_joint3'](['/World/Panda/panda_link2/panda_joint3'], scene=Scene()),
 'panda_joint4': Joint['panda_joint4'](['/World/Panda/panda_link3/panda_joint4'], scene=Scene()),
 'panda_joint5': Joint['panda_joint5'](['/World/Panda/panda_link4/panda_joint5'], scene=Scene()),
 'panda_joint6': Joint['panda_joint6'](['/World/Panda/panda_link5/panda_joint6'], scene=Scene()),
 'panda_joint7': Joint['panda_joint7'](['/World/Panda/panda_link6/panda_joint7'], scene=Scene()),
 'panda_hand_joint': Joint['panda_hand_joint'](['/World/Panda/panda_link7/panda_hand_joint'], scene=Scene()),
 'panda_finger_joint1': Joint['panda_finger_joint1'](['/World/Panda/panda_hand/panda_finger_joint1'], scene=Scene()),
 'panda_finger_joint2': Joint['panda_finger_joint2'](['/World/Panda/panda_hand/panda_f

In [7]:
panda.dof_names

['panda_joint1',
 'panda_joint2',
 'panda_joint3',
 'panda_joint4',
 'panda_joint5',
 'panda_joint6',
 'panda_joint7',
 'panda_finger_joint1',
 'panda_finger_joint2']

In [8]:
panda.dof_positions

tensor([[ 1.1952e-02, -5.6824e-01,  1.2265e-05, -2.8113e+00,  1.7285e-04,
          3.0364e+00,  7.4084e-01,  0.0000e+00,  0.0000e+00]])

Driver add-on

In [9]:
panda.driver.dof_target_positions

tensor([[ 0.0120, -0.5700,  0.0000, -2.8100,  0.0000,  3.0370,  0.7410,  0.0000,
          0.0000]])

In [10]:
panda.driver.dof_stiffnesses

tensor([[22918.3125, 22918.3125, 22918.3125, 22918.3125, 22918.3125, 22918.3125,
         22918.3125,   400.0000,     0.0000]])

Planner add-on

In [11]:
planner = panda.planner(
    base_link="panda_link0",
    end_link="panda_hand",
)

In [ ]:
# TODO
# await scene.viewer.show(mode="editing")

extension omni.kit.widget.cache_indicator-3.0.7 has a [python.pipapi] entry, but use_online_index=true is not set. It doesn't do anything and can be removed.


In [13]:
from robotodo.utils.pose import Pose

# TODO NOTE start the simulation so that the robot can move
async with scene.play():
    # TODO FIXME illegal mem access
    # TODO doc global pose
    await panda.driver.execute_action(
        planner.compute_action({"target_pose_from_base": Pose([.5, .5, .5])}),
        position_error_limit=1,
        velocity_error_limit=1,
    )

kinematics_fused_cu not found, JIT compiling...
geom_cu binary not found, jit compiling...
tensor_step_cu not found, jit compiling...
lbfgs_step_cu not found, JIT compiling...
line_search_cu not found, JIT compiling...
Batch mode enable graph is only supported with num_graph_seeds==1


In [14]:
# await scene.step()
panda.dof_positions

tensor([[-1.3851e+00, -1.7246e+00,  1.1919e+00, -1.5175e+00, -1.2898e+00,
          1.8985e+00,  5.6228e-01,  1.5726e-06,  2.5960e-06]])

In [15]:
# TODO show users the pose read from end link

## Advanced Topics

### Batched planning and execution

In [16]:
from robotodo.engines.isaac.articulation import Articulation

panda_batch = Articulation.load(
    "/World/Panda{0..10}",
    "https://omniverse-content-production.s3-us-west-2.amazonaws.com/Assets/Isaac/5.0/Isaac/Robots/FrankaRobotics/FrankaPanda/franka.usd",
    scene=scene,
)
panda_batch

Articulation(['/World/Panda0', '/World/Panda1', '/World/Panda2', '/World/Panda3', '/World/Panda4', '/World/Panda5', '/World/Panda6', '/World/Panda7', '/World/Panda8', '/World/Panda9', '/World/Panda10'], scene=Scene())

In [17]:
import numpy
from robotodo.utils.pose import Pose

# TODO NOTE ensure sufficient space between robots to avoid collisions
panda_batch.pose = Pose(
    p=numpy.linspace([0, 1, 0], [0, 25, 0], num=len(panda_batch.path))
)

In [18]:
planner_batch = panda_batch.planner(
    base_link="panda_link0",
    end_link="panda_hand",
)

In [19]:
from robotodo.utils.pose import Pose

# TODO NOTE start the simulation so that the robot can move
async with scene.play():
    await panda_batch.driver.execute_action(
        planner_batch.compute_action({"target_pose_from_base": Pose([.5, 0, .5])}),
        position_error_limit=1,
        velocity_error_limit=1,
    )

Batch mode enable graph is only supported with num_graph_seeds==1


In [20]:
panda_batch.dof_positions.shape

torch.Size([11, 9])