# Articulations (Robots)

TODO WIP
TODO explain what articulations are

In [1]:
from robotodo.engines.isaac.scene import Scene

scene = Scene.load(
    "https://omniverse-content-production.s3-us-west-2.amazonaws.com/Assets/Isaac/5.0/Isaac/Environments/Grid/default_environment.usd",
)

[Warning] PYTHONPATH: path doesn't exist (/home/sysadmin/lab/robotodo-platform/.conda/lib/python3.11/site-packages/isaacsim/exts/isaacsim.simulation_app)
[Warning] PYTHONPATH: path doesn't exist (/home/sysadmin/lab/robotodo-platform/.conda/lib/python3.11/site-packages/isaacsim/extsDeprecated/omni.isaac.kit)
[Warning] Unable to expose 'isaacsim.simulation_app' API: Extension not found

|---------------------------------------------------------------------------------------------|
| Driver Version: 535.247.01    | Graphics API: Vulkan
|=============================================================================================|
| GPU | Name                             | Active | LDA | GPU Memory | Vendor-ID | LUID       |
|     |                                  |        |     |            | Device-ID | UUID       |
|     |                                  |        |     |            | Bus-ID    |            |
|----------------------------------------------------------------------------

2025-12-10T10:58:23Z s] [Error] [omni.kit.renderer.plugin] IRendererImpl::startup called multiple times, ignoring this invocation
2025-12-10T10:58:24Z [2,249ms] [Error] [omni.syntheticdata.scripts.extension] SyntheticData extension needs at least a stageFrameHistoryCount of 3


Warp 1.10.1 initialized:
   CUDA Toolkit 12.8, Driver 12.2
   Devices:
     "cpu"      : "CPU"
     "cuda:0"   : "NVIDIA GeForce RTX 3090" (24 GiB, sm_86, mempool enabled)
   Kernel cache:
     /home/sysadmin/.cache/warp/1.10.1
Warp DeprecationWarning: The `warp.sim` module is deprecated and will be removed in v1.10. Please transition to using the forthcoming Newton library instead.


2025-12-10T10:58:26Z [4,382ms] [Error] [carb.graphics-vulkan.plugin] Could not get NGX parameters block because NGX isn't enabled.
2025-12-10T10:58:26Z [4,382ms] [Error] [carb.graphics-vulkan.plugin] Failed to create NGX context.
2025-12-10T10:58:27Z [4,459ms] [Error] [rtx.optixdenoising73.plugin] Failed to create an Optix adaptor for device 0


In [ ]:
# TODO remind users to use viewer if need be
# scene.viewer.mode = "editing"
# scene.viewer.show()

In [2]:
from robotodo.engines.isaac.articulation import Articulation

panda = Articulation.load(
    "/World/Panda",
    "https://omniverse-content-production.s3-us-west-2.amazonaws.com/Assets/Isaac/5.0/Isaac/Robots/FrankaRobotics/FrankaPanda/franka.usd",
    scene=scene,
)
panda

Articulation(['/World/Panda'], scene=Scene())

In [3]:
# TODO
# panda.viewer.show()

TODO inform users abt urdf support

In [4]:
panda.links

{'panda_link0': Body(['/World/Panda/panda_link0'], scene=Scene()),
 'panda_link1': Body(['/World/Panda/panda_link1'], scene=Scene()),
 'panda_link2': Body(['/World/Panda/panda_link2'], scene=Scene()),
 'panda_link3': Body(['/World/Panda/panda_link3'], scene=Scene()),
 'panda_link4': Body(['/World/Panda/panda_link4'], scene=Scene()),
 'panda_link5': Body(['/World/Panda/panda_link5'], scene=Scene()),
 'panda_link6': Body(['/World/Panda/panda_link6'], scene=Scene()),
 'panda_link7': Body(['/World/Panda/panda_link7'], scene=Scene()),
 'panda_hand': Body(['/World/Panda/panda_hand'], scene=Scene()),
 'panda_leftfinger': Body(['/World/Panda/panda_leftfinger'], scene=Scene()),
 'panda_rightfinger': Body(['/World/Panda/panda_rightfinger'], scene=Scene())}

In [5]:
panda.joints

{'panda_joint1': Joint['panda_joint1'](['/World/Panda/panda_link0/panda_joint1'], scene=Scene()),
 'panda_joint2': Joint['panda_joint2'](['/World/Panda/panda_link1/panda_joint2'], scene=Scene()),
 'panda_joint3': Joint['panda_joint3'](['/World/Panda/panda_link2/panda_joint3'], scene=Scene()),
 'panda_joint4': Joint['panda_joint4'](['/World/Panda/panda_link3/panda_joint4'], scene=Scene()),
 'panda_joint5': Joint['panda_joint5'](['/World/Panda/panda_link4/panda_joint5'], scene=Scene()),
 'panda_joint6': Joint['panda_joint6'](['/World/Panda/panda_link5/panda_joint6'], scene=Scene()),
 'panda_joint7': Joint['panda_joint7'](['/World/Panda/panda_link6/panda_joint7'], scene=Scene()),
 'panda_hand_joint': Joint['panda_hand_joint'](['/World/Panda/panda_link7/panda_hand_joint'], scene=Scene()),
 'panda_finger_joint1': Joint['panda_finger_joint1'](['/World/Panda/panda_hand/panda_finger_joint1'], scene=Scene()),
 'panda_finger_joint2': Joint['panda_finger_joint2'](['/World/Panda/panda_hand/panda_f

In [6]:
panda.dof_names

['panda_joint1',
 'panda_joint2',
 'panda_joint3',
 'panda_joint4',
 'panda_joint5',
 'panda_joint6',
 'panda_joint7',
 'panda_finger_joint1',
 'panda_finger_joint2']

In [7]:
panda.dof_positions

tensor([[ 1.1952e-02, -5.6824e-01,  1.2265e-05, -2.8113e+00,  1.7285e-04,
          3.0364e+00,  7.4084e-01,  0.0000e+00,  0.0000e+00]])

Driver add-on

In [8]:
panda.driver.dof_target_positions

tensor([[ 0.0120, -0.5700,  0.0000, -2.8100,  0.0000,  3.0370,  0.7410,  0.0000,
          0.0000]])

In [9]:
panda.driver.dof_stiffnesses

tensor([[22918.3125, 22918.3125, 22918.3125, 22918.3125, 22918.3125, 22918.3125,
         22918.3125,   400.0000,     0.0000]])

Planner add-on

In [10]:
planner = panda.planner(
    base_link="panda_link0",
    end_link="panda_hand",
)

In [11]:
# TODO NOTE start the simulation so that the robot can move
scene.autostepping = True

In [12]:
from robotodo.utils.pose import Pose

# TODO doc global pose
await panda.driver.execute_action(
    planner.compute_action({"target_pose_from_base": Pose([.5, .5, .5])}),
    position_error_limit=1,
    velocity_error_limit=1,
)

kinematics_fused_cu not found, JIT compiling...
geom_cu binary not found, jit compiling...
tensor_step_cu not found, jit compiling...
lbfgs_step_cu not found, JIT compiling...
line_search_cu not found, JIT compiling...
Batch mode enable graph is only supported with num_graph_seeds==1


In [13]:
# await scene.step()
panda.dof_positions

tensor([[-1.5134e+00, -1.7462e+00,  1.2217e+00, -1.4606e+00, -1.3085e+00,
          1.8856e+00,  5.6014e-01,  2.1421e-06,  0.0000e+00]])

In [14]:
# TODO show users the pose read from end link

In [15]:
# scene.viewer.show()

## Advanced Topics

### Batched planning and execution

In [16]:
from robotodo.engines.isaac.articulation import Articulation

panda_batch = Articulation.load(
    "/World/Panda{0..10}",
    "https://omniverse-content-production.s3-us-west-2.amazonaws.com/Assets/Isaac/5.0/Isaac/Robots/FrankaRobotics/FrankaPanda/franka.usd",
    scene=scene,
)
panda_batch

Articulation(['/World/Panda0', '/World/Panda1', '/World/Panda2', '/World/Panda3', '/World/Panda4', '/World/Panda5', '/World/Panda6', '/World/Panda7', '/World/Panda8', '/World/Panda9', '/World/Panda10'], scene=Scene())

In [17]:
import numpy
from robotodo.utils.pose import Pose

# TODO NOTE ensure sufficient space between robots to avoid collisions
panda_batch.pose = Pose(
    p=numpy.linspace([0, 1, 0], [0, 25, 0], num=len(panda_batch.path))
)

In [18]:
planner_batch = panda_batch.planner(
    base_link="panda_link0",
    end_link="panda_hand",
)

In [19]:
# TODO NOTE start the simulation so that the robot can move
scene.autostepping = True

In [20]:
from robotodo.utils.pose import Pose

await panda_batch.driver.execute_action(
    planner_batch.compute_action({"target_pose_from_base": Pose([.5, 0, .5])}),
    position_error_limit=1,
    velocity_error_limit=1,
)

Batch mode enable graph is only supported with num_graph_seeds==1


In [21]:
panda_batch.dof_positions.shape

torch.Size([11, 9])